# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/zendertv/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ZenderDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZenderDemo
  pod 'Zender'
  # pod 'Zender/Youtube'

  target 'ZenderDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZenderDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
